import 'react-phone-input-2/lib/style.css';

import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import PhoneInput from 'react-phone-input-2';

const Home: NextPage = () => {
	const router = useRouter();
	const [phoneNumber, setPhoneNumber] = useState<string>();

	const handleSubmit = async () => {
		if (phoneNumber) {
			const res = await axios.post('/api/welcome', { phoneNumber });
			console.log(res);
			router.push('/success');
		}
	};

	return (
		<div>
			<Head>
				<title>BeFit</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex h-screen justify-center ">
				<div className="flex flex-col items-center gap-5 bg-black pt-[5%] text-center text-white xs:w-[90%] sm:w-[640px] sm:px-10">
					<div className="py-6 text-4xl font-semibold">BeFit.</div>
					<div>Let&apos; s make fitness a habit, together.</div>
					<div>Enter your phone number to join the revolution 💪🏽</div>
					<div>
						<PhoneInput
							country={'us'}
							placeholder="Enter phone number"
							inputClass="rounded-lg bg-white focus:outline-none text-black"
							dropdownClass="text-black"
							value={phoneNumber}
							onChange={setPhoneNumber}
						/>
					</div>
					<button
						className="rounded-full bg-white px-6 py-2 font-semibold text-black"
						onClick={handleSubmit}
					>
						🔥 GET FIT 🔥
					</button>
					{/* <div className="text-sm font-light text-gray-500">Learn more</div> */}
					<div className="text-sm font-light text-gray-500">
						NOTE: We are in no way related to BeReal.
					</div>
				</div>
			</div>
		</div>
	);
};

export default Home;
