import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>BeFit</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex h-screen justify-center ">
				<div className="flex flex-col items-center gap-5 bg-black pt-[5%] text-center text-white xs:w-[90%] sm:w-[640px] sm:px-10">
					<div className="py-6 text-4xl font-semibold">BeFit.</div>
					<div>Nice! Check your texts to proceed 💪🏽</div>
					<div className="text-sm font-light text-gray-500">
						NOTE: We are in no way related to BeReal.
					</div>
				</div>
			</div>
		</div>
	);
};

export default Home;
